# Generated by Django 3.2.7 on 2021-09-29 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_gametype_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
